name: Publish to NPM

on:
  push:
    branches:
      - main

permissions:
  contents: write  
  packages: write 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install && npm install typescript

      - name: Ensure Initial Tag Exists
        run: |
          git fetch --tags
          if [ -z "$(git tag)" ]; then
            git tag v0.1.0
            git push origin v0.1.0
          fi

      - name: Set up Semantic Versioning
        id: version
        run: |
          git fetch --tags
          npx standard-version --dry-run
          VERSION=$(npx -q standard-version --dry-run | grep "tagging release" | awk '{print $3}')
          echo "new_release_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build the project
        run: npm run build

      - name: Publish to NPM
        if: steps.version.outputs.new_release_version != ''
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public

      - name: Push Changes
        if: steps.version.outputs.new_release_version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git push --follow-tags origin main
